{
 "title": "Capacity management demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Client Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_requests_total{status=\"200\"}[30s]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(client_requests_total{status!=\"200\"}[30s]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests count" }
   ],
   "targets": [
    { "expr": "proxy_inflight_requests", "legendFormat": "in-flight" },
    { "expr": "proxy_target_inflight_requests", "legendFormat": "target" }
   ]
  },
  {
   "title": "Origin Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(origin_requests_total{status=\"200\"}[30s]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(origin_requests_total{status=\"429\"}[30s]))",
     "legendFormat": "429"
    }
   ]
  },
  {
   "title": "Origin Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "rate(origin_request_duration_seconds_sum[30s]) / rate(origin_request_duration_seconds_count[30s])",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(origin_request_duration_seconds_bucket[30s])) by (le))",
     "legendFormat": "p50th (median)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(origin_request_duration_seconds_bucket[30s])) by (le))",
     "legendFormat": "p99th"
    }
   ]
  }
 ]
}