name: Go
on:
  push:

jobs:
  goreleaser-dryrun:
    runs-on: ubuntu-latest
    steps:
    - name: Go Formatter
      # You may pin to the exact commit or the version.
      # uses: sladyn98/auto-go-format@6557e892479fd174506c48cb34017c51399d492b
      uses: sladyn98/auto-go-format@v0.0.1

  
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.31
          #github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout=2m
          only-new-issues: false
          working-directory: .
